<?php

return [

    '@meta' => [

        'language' => 'Deutsch',
        'author'   => 'Julius Elias Sohn',

        'date' => [
            'shortdays'   => ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'],
            'longdays'    => ['Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag', 'Sonntag'],
            'shortmonths' => ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
            'longmonths'  => ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember']
        ]
    ],


    // Common
    'Authenticate'  => 'Login',
    'Welcome back!'  => 'Wilkommen zurück!',
    'Dashboard'  => 'Dashboard',
    'General'  => 'Allgemein',
    'Settings' => 'Einstellungen',
    'Logout'   => 'Abmelden',
    'Info'     => 'Info',
    'Filter by name...' => 'Nach Namen filtern...',
    'Save' => 'Speichern',
    'Delete'  => 'Löschen',
    'Cancel' => 'Abbrechen',
    'Entry' => 'Eintrag',
    'Entries' => 'Einträge',
    'Field' => 'Feld',
    'Fields' => 'Felder',
    'Date' => 'Datum',
    'Latest' => 'Aktuell',
    'Group' => 'Gruppe',
    'No group' => 'Keine Gruppe',
    'Modified' => 'Modifiziert',
    'Today'  => 'Heute',
    'Info'  => 'Info',
    'Language' => 'Sprache',
    'System' => 'System',
    'Meta fields' => 'Metadaten',
    'Are you sure?' => 'Sind Sie sicher?',
    'Search...' => 'Suchen...',
    'Activity' => 'Aktivitäten',
    '%s logged in' => '%s hat sich eingeloggt.',

    // Login
    'Authenticate Please!' => 'Bitte anmelden!',
    'Welcome back!' => 'Willkommen zurück!',
    'Please login by using your auth credentials.' => 'Bitte geben Sie Ihre Login Daten ein.',
    'Authenticate' => 'Anmelden',
    'Login failed' => 'Login fehlgeschlagen',

    // Accounts
    'Account'  => 'Konto',
    'Accounts' => 'Konten',
    'Name' => 'Name',
    'Username' => 'Benutzername',
    'Email' => 'Email',
    'Password' => 'Passwort',
    'New Password' => 'Neues Password',
    'Create account' => 'Konto erstellen',
    'Leave the password field empty to keep your current password.' => 'Passwortfeld leer lassen, um das aktuelle Passwort zu behalten.',
    'Edit account' => 'Konto editieren',
    'Edit account settings' => 'Kontoeinstellungen editieren',
    'Delete account' => 'Konto löschen',
    'Account saved!' => 'Account gespeichert',

    //Groups
    'Group'=>'Gruppe',
    'Groups'=>'Gruppen',
    'Add group'=>'Guppe hinzufügen',
    'Access'=>'Rechte',
    'Manage account groups and permissions' => 'Benutzergruppen und Rechte verwalten',
    'Media root path' => 'Zugriff auf Medienordner',

    // Addons
    'Addons'   => 'Erweiterungen',
    'No additional addons installed.' => 'Keine zusätzlichen Erweiterungen sind installiert.',

    // Collections
    'Collections' => 'Kollektionen',
    'Collection' => 'Kollektion',
    'Show entries' => 'Einträge anzeigen',
    'Create new entry' => 'Neuen Eintrag erstellen',
    'Create a collection' => 'Kollektion erstellen',
    'Add collection' => 'Kollektion hinzufügen',
    'Edit collection' => 'Kollektion editieren',
    'Delete collection' => 'Kollektion löschen',
    'You don\'t have any collections created.' => 'Sie haben noch keine Kollektionen erstellt.',
    'Save Collection' => 'Kollektion speichern',
    'Add entry' => 'Eintrag hinzufügen',
    'Edit entry' => 'Eintrag editieren',
    'Delete entry' => 'Eintrag löschen',
    'It seems you don\'t have any fields created.' => 'Es scheint Sie haben noch keine Felder erstellt.',
    'Goto entries' => 'Einträge anzeigen',
    'Fields on entries list page' => 'Felder anzeigen auf der Übersichtsseite',
    'Order entries on list page' => 'Einträge ordnen auf der Übersichtsseite',
    'created' => 'erstellt',
    'modified' => 'modifiziert',
    'descending' => 'absteigend',
    'ascending' => 'aufsteigend',
    'Collection removed' => 'Kollektion entfernt',
    'Collection saved!' => 'Kollektion gespeichert!',
    'Entry removed' => 'Eintrag entfernt',
    'Entry saved!' => 'Eintrag gespeichert!',

    // Mediamanager

    'Mediamanager' => 'Medienmanager',
    'Bookmarks' => 'Favoriten',
    'Folders' => 'Ordner',
    'Folder' => 'Ordner',
    'Files' => 'Dateien',
    'File' => 'Datei',
    'Upload files' => 'Dateien hochladen',
    'Find files...' => 'Dateien suchen...',
    'You have nothing bookmarked.' => 'Sie haben keine Favoriten.',
    'Table mode' => 'Tabellenansicht',
    'List mode' => 'Kachelansicht',
    'Folders hidden via filter' => 'Ordner versteckt via Filter',
    'Files hidden via filter' => 'Dateien versteckt via Filter',
    'All' => 'Alle',
    'Show files + directories' => 'Zeige Dateien + Ordner',
    'Show only directories' => 'Zeige nur Ordner',
    'Show only files' => 'Zeige nur Dateien',
    'Bookmark folder' => 'Ordner zu Lesezeichen',
    'Rename folder' => 'Ordner umbenennen',
    'Delete folder' => 'Ordner löschen',
    'Bookmark file' => 'Datei favorisieren',
    'Rename file' => 'Datei umbenennen',
    'Delete file' => 'Datei löschen',
    'Download file' => 'Datei herunterladen',
    'Size' => 'Grösse',
    'Last modified' => 'Zuletzt bearbeitet',
    'This folder is empty.' => 'Dieser Ordner ist leer.',
    'Save file' => 'Datei speichern',
    'Close file' => 'Datei schliessen',
    'Do you really want to remove %s ?' => 'Wollen Sie wirklich %s entfernen?',
    'This file is not writable!' => 'Diese Datei ist schreibgeschützt!',
    'Please enter new name:' => 'Bitte geben Sie einen neuen Namen an:',
    'Please enter name:' => 'Bitte geben Sie einen Namen an:',
    '%s is already bookmarked.' => '%s wurde bereits favorisiert',
    '%s bookmarked.' => '%s wurde zu den Favoriten hinzugefügt.',
    'Do you really want to remove %s ?' => 'Wollen Sie wirklich %s entfernen?',

    // Regions
    'Regions' => 'Regionen',
    'Region' => 'Region',
    'Add region' => 'Region hinzufügen',
    'Create a region' => 'Eine Region erstellen',
    'Edit region' => 'Region editieren',
    'Delete region' => 'Region löschen',
    'You don\'t have any regions created.' => 'Sie haben bisher keine Region erstellt.',
    'Form' => 'Formular',
    'Template' => 'Template',
    'Region fields' => 'Regionsfelder',
    'Form fields' => 'Formularfelder',
    'Manage form' => 'Formular bearbeiten',
    'Done' => 'Fertig',
    'This region has no fields yet.' => 'Diese Region hat aktuell keine Felder.',
    'Add field' => 'Feld hinzufügen',
    'Insert form field' => 'Formfeld einfügen',
    'You have no fields added.' => 'Sie haben noch keine Felder angelegt.',
    'Embed region snippet' => 'Embed region snippet',
    'Save Region' => 'Region speichern',
    'Region removed' => 'Region speichern',
    'Region saved!' => 'Region gespeichert!',

    // Backups
    'Backups' => 'Backups',
    'You don\'t have any backups created.' => 'Sie haben keine Backups erstellt',
    'Create a new backup' => 'Neues Backup erstellen',
    'Backups are located here' => 'Backups befinden sich hier',
    'Download backup' => 'Backup herunterladen',
    'Delete backup' => 'Backup löschen',
    'Creating backup...' => 'Backup wird erstellt...',
    'Backup created' => 'Backup wurde erstellt',
    'Backup deleted' => 'Backup wurde gelöscht',

    // Forms
    'Forms' => 'Formulare',
    'Form' => 'Formular',
    'Add form' => 'Formular hinzufügen',
    'Show all forms' => 'Alle Formulare anzeigen',
    'Create a form' => 'Eine Formular erstellen',
    'Edit form' => 'Formular editieren',
    'Delete form' => 'Formular löschen',
    'You don\'t have any forms created.' => 'Sie haben bisher keine Formular erstellt.',
    'Form' => 'Formular',
    'Template' => 'Template',
    'Form fields' => 'Formularsfelder',
    'Form fields' => 'Formularfelder',
    'Manage form' => 'Formular bearbeiten',
    'Done' => 'Fertig',
    'This form has no fields yet.' => 'Diese Formular hat aktuell keine Felder.',
    'Add field' => 'Feld hinzufügen',
    'Insert form field' => 'Formfeld einfügen',
    'You have no fields added.' => 'Sie haben noch keine Felder angelegt.',
    'Embed form snippet' => 'Embed region snippet',
    'Save form' => 'Formular speichern',
    'Save form data' => 'Formulardaten speichern',
    'Form removed' => 'Formular speichern',
    'Form saved!' => 'Formular gespeichert!',
    'Email form data to this adress' => 'Sende die Formulardaten an diese Adresse',
    'Leave the field empty if you don\'t want to recieve any form data via email.' => 'Lassen Sie Feld leer, wenn Sie die Fomrulardaten nicht zugesendet bekommen möchten.',
    'It is important to prefix the form fields with %s .' => 'Es ist wichtig, dass der Formularname mit %s beginnt.',

    //API Settings
    'You have no api token generated yet.' => 'Sie haben noch kein API Token generiert.',
    'Generate api token' => 'API Token generieren',


     // Galleries
    'Galleries' => 'Gallerien',
    'Gallery' => 'Gallerie',
    'Add gallery' => 'Gallerie hinzufügen',
    'All galleries' => 'Alle Gallerien',
    'Create groups to organize your galleries.' => 'Erstellen Sie Gruppen um Ihre Gallerien zu verwalten.',
    'Create new group' => 'Neue Gruppe erstellen',
    'Show all galleries' => 'Alle Gallerien anzeigen',
    'Create a gallery' => 'Eine Gallerie erstellen',
    'Edit gallery' => 'Gallerie editieren',
    'Delete gallery' => 'Gallerie löschen',
    'You don\'t have any galleries created.' => 'Sie haben bisher keine Gallerie erstellt.',
    'Gallery' => 'Gallerie',
    'Template' => 'Template',
    'Manage gallery' => 'Gallerie bearbeiten',
    'Done' => 'Fertig',
    'This gallery has no fields yet.' => 'Diese Gallerie hat aktuell keine Felder.',
    'Add images to gallery' => 'Bilder zur Gallerie hinzufügen',
    'Single image' => 'Einzelnes Bild',
    'Images from folder' => 'Bilder aus einem Ordner',
    '%s image(s) imported' => '%s Bilder hinzugefügt',
    'Insert gallery field' => 'Formfeld einfügen',
    'You have no fields added.' => 'Sie haben noch keine Felder angelegt.',
    'Embed gallery snippet' => 'Embed region snippet',
    'Save gallery' => 'Gallerie speichern',
    'Save gallery data' => 'Galleriedaten speichern',
    'Gallery removed' => 'Gallerie speichern',
    'Gallery saved!' => 'Gallerie gespeichert!',
    'You don\'t have any images in this gallery.'=>'Sie haben noch keine Bilder zu dieser Gallerie hinzugefügt.'
];
